name: quran_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-131.0.dev <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.1
  connectivity_plus: ^5.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  just_audio: ^0.9.36
  share_plus: ^5.0.0
  curved_navigation_bar: ^1.0.3
  provider:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/svg/
