name: gojek_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

fonts:
  - family: SF-Pro-Display
    fonts:
      - asset: assets/fonts/SF-Pro-Display-Regular.otf
      - asset: assets/fonts/SF-Pro-Display-Semibold.otf 
        weight: 600
      - asset: assets/fonts/SF-Pro-Display-Bold.otf
        weight: 700
       
